"""Run every diagnostic script and assemble analysis/phase1_diagnostics.md from phase1_diagnostics.template.md.

Usage:  python analysis/assemble.py      (from the repo root; read-only on engine/reporter/pre-registration/data)
Tables in the template appear as {{table:NAME}} and are replaced verbatim with analysis/out/NAME.md, so every number in the report
is generated by code; the narrative around the tables is hand-written.
"""
import contextlib
import io
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import adverse_selection  # noqa: E402
import fee_breakeven  # noqa: E402
import fill_model_compare  # noqa: E402
import latency_sensitivity  # noqa: E402
import verify_edge  # noqa: E402
from common import OUT  # noqa: E402


def main():
    for mod in (fee_breakeven, adverse_selection, fill_model_compare, latency_sensitivity, verify_edge):
        with contextlib.redirect_stdout(io.StringIO()):
            mod.main()
    tpl = (HERE / "phase1_diagnostics.template.md").read_text(encoding="utf-8")

    def sub(m):
        return (OUT / f"{m.group(1)}.md").read_text(encoding="utf-8").strip()
    text = re.sub(r"\{\{table:([a-z_]+)\}\}", sub, tpl)
    (HERE / "phase1_diagnostics.md").write_text(text, encoding="utf-8")
    print(f"wrote {HERE / 'phase1_diagnostics.md'} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
